---
title: ""
output:
  html_document:
    theme:
      bootswatch: simplex
      base_font:
        google: "Open Sans"
params:
  
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(gt)

knitr::opts_chunk$set(echo = FALSE)
```

Please find attached the results of the readmission prediction for new patients.

```{r}

## Create a data frame of predictions


## Create a customized table of predictions
table <-
  
  fmt_percent(decimals = 0) |>
  cols_label(.list = c("id" = "Patient ID",
                       "pred" = "Prediction",
                       "no_readmit" = "Probability of No Readmission",
                       "yes_readmit" = "Probability of Readmission")) |>
  opt_row_striping() |>
  cols_align(align = "left", columns = c(id)) |>
  cols_align(align = "center", columns = "pred":"yes_readmit") |>
  tab_style(
    style = list(
      cell_fill("grey20"),
      cell_text(
        color = "white",
        align = "center",
        v_align = "middle"
      )
    ),
    locations = cells_column_labels(columns = everything())
  ) |>
  tab_style(style = cell_borders(color = "#e9ecef", weight = px(1.5)),
            locations = cells_body()) |>
  tab_options(
    column_labels.font.size = px(15),
    data_row.padding = px(16),
    table.font.size = px(14)
  )

## Print the table
table
```

Click here to view the complete data and prediction.
